### ISSUE TITLE
[BUG] Returned bing results low quality

### ISSUE THREAD

**Issue by k4lizen** [hearchco/agent#172]
**Describe the bug**
When searching bing through hearchco, the results seem to be of lower quality and often include french in them.

**To Reproduce**
https://hearch.co/search?q=%21bi+how+to+sell+your+new+car

**Expected behavior**
I would expect the results to be the same as the ones you get by searching bing directly. https://www.bing.com/search?q=how+to+sell+your+new+car
The results seem to be correct when the hearchco CLI is used.

**Screenshots**
![image](https://github.com/hearchco/hearchco/assets/124312252/45efa736-156a-469c-a215-0d5a26c57913)
![image](https://github.com/hearchco/hearchco/assets/124312252/64a92b41-a908-4dd4-bbb0-801e7cfeaa80)

**Comment by aleksasiriski** [comment]
> often include french in them

This is most likely related to the fact that hearchco servers are located in fly.io CDG (Paris) region. We need to force Bing (and all search engines) to give standard / en-US / default results whatever the location of the server somehow.

**Comment by k4lizen** [comment]
Can confirm, some countries give US-en results, but VPN-ing to Paris and searching through the CLI gives the same results as the website does.
