### ISSUE TITLE
[BUG] Category isn't accounted for in the cache

### ISSUE THREAD

**Issue by aleksasiriski** [hearchco/agent#205]
**Describe the bug**
When searching with query it gets cached by default but the cache is category independant, so by searching "cat" in general search, when requesting "cat" with image search you get general results, not image results. This applies to all categories.

**To Reproduce**
Search something with the default cache enabled mode, afterwards search the same query with a different category.

**Expected behavior**
Categories should be a part of the cache string key.

**Comment by k4lizen** [comment]
Cache could be per-engine, and then searching could be done with more granularity, and not re-searching stuff thats in different categories but has overlap. All results are then resorted.

**Comment by aleksasiriski** [comment]
Duplicate of #248
