### ISSUE TITLE
[FEAT] Suggestions API

### ISSUE THREAD

**Issue by GGLVXD** [hearchco/agent#327]
Add **ACTUAL** autocomplete that uses some or one search engine to get autocomplete data.

**Comment by aleksasiriski** [comment]
That's the plan :) After the refactor I was planning on doing that as the next big feature, you are also more than welcome to contribute!

My idea was to poll autocomplete data from multiple engines and afterwards combine it before sending it to the user, as with general and images.

**Comment by GGLVXD** [comment]
Im not the best programmer but i can try to help

**Comment by aleksasiriski** [comment]
It seems that is shouldn't be difficult to implement.
Google: `https://suggestqueries.google.com/complete/search?client=firefox&q=<query>`

Others that implement this for browsers can be found as well.
I will work on this in a week or two.

**Comment by aleksasiriski** [comment]
Also for DDG, I found [opensearch.xml](https://duckduckgo.com/opensearch.xml?atb=v435-2__) which has the same standard for [search suggestions api](https://duckduckgo.com/ac/?q={searchTerms}&type=list)

**Comment by aleksasiriski** [comment]
Agent/backend has the support to retrieve suggestions either via our custom JSON response or the OpenSearch Suggestions API standard. This means that browsers can also use Hearchco for suggestion as well as that our frontend has easier to work with types (the standard is awful IMHO).

**Comment by aleksasiriski** [comment]
Work on the backend is done, waiting for some final touches if I think of any and to test the OpenSearch Suggestions API spec in browsers, afterwards I will work on the frontend to support this nicely.

**Comment by aleksasiriski** [comment]
This is now completely supported on frontend and in browsers. Please open any issues in the relevant repos if you find any bugs!
