### ISSUE TITLE
[BUG] JSON.parse error

### ISSUE THREAD

**Issue by k4lizen** [hearchco/agent#375]
![image](https://github.com/user-attachments/assets/ab5269ef-8003-456a-a18c-b75de9c34e6e)
Search query: `fear & hunger steam`

**Comment by aleksasiriski** [comment]
I noticed this once recently after my infra changes, will have to investigate if it's a Lambda crashing / some bug in agent/frontend or just another case of old cache resulting in wrong JS/JSON

**Comment by aleksasiriski** [comment]
It seems that any query starting with `fear+%26` is failing

**Comment by aleksasiriski** [comment]
This is a bug on frontend since it can't be replicated on the agent, moving there.

**Comment by matijakljajic** [comment]
@aleksasiriski Just so you know, you could have just transferred it to another repo with:
![image](https://github.com/user-attachments/assets/e5dd66d2-637b-4bef-938e-23d844a03ad8)
